import torch
import torch.nn as nn
import torchaudio

# 1. 2025/2026 Recommended Audio Core (Wav2Vec / Spectrogram CNN)
class AudioExtractor(nn.Module):
    def __init__(self, use_wav2vec=False):
        super(AudioExtractor, self).__init__()
        self.use_wav2vec = use_wav2vec
        
        if self.use_wav2vec:
            # 2025/2026 SOTA: Pre-trained Wav2Vec (or similar high-accuracy audio models)
            # Extracted features from voice patterns for synthetic cloning detection.
            # Here we wrap a generic torchaudio Wav2Vec2 bundle as an example.
            try:
                bundle = torchaudio.pipelines.WAV2VEC2_BASE
                self.wav2vec = bundle.get_model()
                # 768 is the standard output dimension for base Wav2vec2
                self.feature_reduction = nn.Linear(768, 256)
            except Exception as e:
                print("Warning: Wav2Vec failed to load, falling back to CNN", e)
                self.use_wav2vec = False

        if not self.use_wav2vec:
            # Fallback: Hybrid CNN + LSTM for processing Audio Spectrograms 
            # (Detects voice-video sync mismatches / cloning artifacts)
            self.cnn = nn.Sequential(
                nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
                nn.ReLU(),
                nn.MaxPool2d(kernel_size=2, stride=2),
                nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
                nn.ReLU(),
                nn.MaxPool2d(kernel_size=2, stride=2),
                nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
                nn.ReLU(),
                nn.AdaptiveAvgPool2d((1, 10)) # pool down into a sequence of length 10
            )
            # LSTM over the time sequence generated by the CNN
            self.lstm = nn.LSTM(input_size=128, hidden_size=256, num_layers=2, batch_first=True, dropout=0.3)
            
    def forward(self, x):
        """
        x could be raw waveforms (for Wav2Vec) OR MelSpectrograms (for CNN+LSTM)
        Outputs a 256-dimensional feature vector.
        """
        if self.use_wav2vec:
            # Wav2vec expects raw waveforms: (batch, time)
            features, _ = self.wav2vec(x) # (batch, time, 768)
            # Pool across time to get a single vector per audio sample
            pooled_features = torch.mean(features, dim=1) # (batch, 768)
            audio_out = self.feature_reduction(pooled_features) # (batch, 256)
        else:
            # Spectrograms expect: (batch, 1 channel, freq, time)
            cnn_out = self.cnn(x) # (batch, 128, 1, 10)
            cnn_out = cnn_out.squeeze(2).permute(0, 2, 1) # (batch, 10, 128)
            lstm_out, _ = self.lstm(cnn_out) # (batch, 10, 256)
            audio_out = lstm_out[:, -1, :] # final states: (batch, 256)
            
        return audio_out


# 2. 2025/2026 Recommended Attention-Based Multimodal Fusion
class MultimodalFusionNetwork(nn.Module):
    def __init__(self, visual_feature_dim=256, audio_feature_dim=256):
        super(MultimodalFusionNetwork, self).__init__()
        
        # We concatenate both visual (256) + audio (256) into a sequence of [2, 256] length
        # Or, we compress them both natively. 
        self.visual_dim = visual_feature_dim
        self.audio_dim = audio_feature_dim
        
        # Transformer-based Modality Fusion 
        # (Learns interactions between audio cloning artifacts & visual mismatches)
        self.fusion_attention = nn.MultiheadAttention(embed_dim=256, num_heads=8, batch_first=True)
        
        # Final fully connected classifier head (Real/Fake)
        self.classifier = nn.Sequential(
            nn.Linear(256 * 2, 128), # *2 because we concat visual and audio post-attention
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(128, 2)
        )
        
    def forward(self, visual_features, audio_features):
        """
        Dynamically weights which modality (audio or visual) is more suspicious.
        visual_features: (batch, 256) output from DeepfakeDetector
        audio_features: (batch, 256) output from AudioExtractor
        """
        
        # Stack visual and audio features to create a "sequence" of modalities
        # sequence shape: (batch_size, 2 modalities, 256 dimension)
        stacked_modalities = torch.stack([visual_features, audio_features], dim=1)
        
        # Self-Attention across the modalities
        # This will dynamically weight connections between audio/video
        attn_output, attn_weights = self.fusion_attention(
            query=stacked_modalities, 
            key=stacked_modalities, 
            value=stacked_modalities
        )
        
        # Reshape the output of the attention back into a flat vector for the classifier
        # Flattening (batch, 2, 256) -> (batch, 512)
        batch_size = visual_features.size(0)
        flattened_fusion = attn_output.reshape(batch_size, -1)
        
        # Final Prediction Layer
        verdict = self.classifier(flattened_fusion)
        
        # We return the attention weights too (Could be useful for your 'Explainability' UI metric! 
        # e.g., "The model focused 80% on 'Audio' because voice cloning was detected")
        return verdict, attn_weights

# Example usage/tester
if __name__ == "__main__":
    print("Testing 2025/2026 Multimodal Fusion Architecture...")
    
    # 1. Simulate an audio track passing through an Audio Extractor
    audio_net = AudioExtractor(use_wav2vec=False) # fallback to CNN+LSTM for random tensor test
    fake_spectrogram = torch.randn(4, 1, 128, 500) # batch of 4 audio spectrograms
    audio_vector = audio_net(fake_spectrogram)
    print(f"Extracted Audio Features Shape: {audio_vector.shape}")
    
    # 2. Simulate visual frames coming from your existing DeepfakeDetector 
    # (Pretending they are processed into their 256-dim feature representation)
    visual_vector = torch.randn(4, 256) 
    print(f"Extracted Visual Features Shape: {visual_vector.shape}")
    
    # 3. Predict via Attention-Based Fusion
    fusion_net = MultimodalFusionNetwork()
    real_fake_logits, attention = fusion_net(visual_vector, audio_vector)
    
    print(f"Final Real/Fake Prediction Logits: {real_fake_logits.shape}")
    print(f"Attention Weights (Visual vs Audio): {attention.shape}") # Should be (batch, 2, 2)
    print("Architecture built successfully!")
